# Generated by Django 6.0.6 on 2026-07-09 15:57

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(max_length=200)),
                ('image_URL', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=500, null=True)),
                ('instructions_and_rules', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=500, null=True)),
                ('address_and_contact', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Example: <h2>Address: 0000 Street, City, State zipcode <br />or Contact for Address <br />Email: example@gmail.com <br />Phone number: +1(111) 111-1111</h2>', max_length=500, null=True)),
                ('particpating_and_attending', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Example (for displaying): <h3>Participating: 20/30 <br />Attending: 65/90</h3>', max_length=500, null=True)),
                ('event_date', models.DateField()),
                ('public', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.IntegerField(blank=True, default=0, null=True)),
                ('participants', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('image_URL__isnull', True), ('upload_image__isnull', False)), models.Q(('image_URL__isnull', False), ('upload_image__isnull', True)), ('description__isnull', False), _connector='OR'), name='Must submit something to create Event')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_URL', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('post_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=500, null=True)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('image_URL__isnull', True), ('upload_image__isnull', False)), models.Q(('image_URL__isnull', False), ('upload_image__isnull', True)), ('post_text__isnull', False), _connector='OR'), name='Must submit something to create Post')],
            },
        ),
    ]
