# Generated by Django 6.0.6 on 2026-07-09 17:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='instructions_and_rules',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2000, null=True),
        ),
    ]
