# Generated by Django 6.0.6 on 2026-07-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='particpating_and_attending',
            new_name='participating_and_attending',
        ),
    ]
