# Generated by Django 6.0.6 on 2026-07-09 20:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_particpating_and_attending_event_participating_and_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address_and_contact',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Example: <p>Address: 0000 Street, City, State zipcode <br />or Contact for Address <br />Email: example@gmail.com <br />Phone number: +1(111) 111-1111</p>', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participating_and_attending',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Example (for displaying): <p>Participating: 20/30 <br />Attending: 65/90</p>', max_length=500, null=True),
        ),
    ]
