# Generated by Django 6.0.6 on 2026-07-10 00:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_event_address_and_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address_and_contact',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default="Example: <p>Address: 0000 Street, City, State zipcode or ''Contact for Address'' <br />Email: example@gmail.com <br />Phone number: +1(111) 111-1111</p>", max_length=500, null=True),
        ),
    ]
